### PR TITLE
Removed hashtag as token for inline comments

### LINKED ISSUE #347: Hashtags in transaction descriptions are being highlighted as comments
In transaction descriptions that contain a hashtag, the syntax highlighter incorrectly interprets it as a comment. This is misleading and may cause a user to unnecessarily edit a transaction to remove the highlight. Example:

```
2023-08-15 SOBEYS #680 ; The comment starts at this semicolon, but highlighter indicates that it starts at the hashtag
    Liabilities:My Credit Card    -43.42
    Expenses:Groceries             43.42
```

Please see [this discussion](https://www.reddit.com/r/plaintextaccounting/comments/16kfwi8/escaping_special_characters_in_hledger_journals/) for information on how transaction descriptions are parsed. To summarize:

> - transaction descriptions can contain any characters other than semicolon
> - an asterisk and space at the start of the description could be interpreted as a transaction status mark
> - parenthesised text at the start of the description could be interpreted as a transaction code
> - the first pipe character separates payee and note subfields and can not be escaped
> - a semicolon starts a comment and can not be escaped. (# and * do not start a comment except at the start of a line.)
> - comments can contain any characters
> - words followed by a full colon within comments are interpreted as tags

### PR DESCRIPTION
**Pull request by darylwright**
Hashtags are not valid comments unless they are at the start of a line. Inline comments can only start with a semicolon.

fixes #347

### CODE REVIEW

**Comment by mhansen** [comment]
Hi, thanks. Could you add a test? This will help ensure I don’t break this
in future. There are some examples in the repo to copy paste.

**Comment by darylwright** [comment]
I updated the tests and they all pass. I found that I missed transaction line comments for the hashtag and asterisk, so I updated those patterns as well. I ran into problems rebuilding the tests in Windows, so I updated the necessary files to ensure cross-platform testability.

**Comment by darylwright** [comment]
I resolved the above issue with the hashtag. There needed to be a second type of comment to distinguish those that are at the start of the line, and those that come after other content (e.g. transaction comments, posting comments, etc.). I also added support for [asterisk comments](https://hledger.org/1.31/hledger.html#star-comments), with tests.

**Comment by mhansen** [comment]
Thanks. Sorry for the delay -- struggling with the open source projects with a new baby at home, merging now.

**Comment by darylwright** [comment]
> Thanks. Sorry for the delay -- struggling with the open source projects with a new baby at home, merging now.

Thanks so much, and congrats on the new addition to your family!

**Comment by mhansen** [comment]
This is now released in 0.0.11. Thanks!

**Pull request merged**
