### PR TITLE
Account names autocomplete

### PR DESCRIPTION
**Pull request by dmytrokyrychuk**
I've implemented the autocomplete in a separate extension originally. This PR is an attempt to incorporate the autocomplete provider from https://github.com/dmytrokyrychuk/vscode-hledger-extra into hledger-vscode.

I am currently stuck trying to launch this extension with the changes I made. I am getting the following error when compiling the extension:

```
❯ npm run compile 

> hledger-vscode@0.0.7 compile
> tsc -p ./

node_modules/vscode-oniguruma/main.d.ts:6:22 - error TS2304: Cannot find name 'Response'.

6  data: ArrayBuffer | Response;
                       ~~~~~~~~

node_modules/vscode-oniguruma/main.d.ts:11:46 - error TS2304: Cannot find name 'Response'.

11 export function loadWASM(data: ArrayBuffer | Response): Promise<void>;
                                                ~~~~~~~~


Found 2 errors.
```

Does anyone have any ideas about how to fix these errors?

### CODE REVIEW

**Comment by mhansen** [comment]
Hmm, strange. https://github.com/microsoft/vscode-oniguruma is a regex library we use. It's maintained by Microsoft as part of VSCode so it shouldn't be broken...

I'd guess `Response` is the response of the Fetch API: https://developer.mozilla.org/en-US/docs/Web/API/Response. Maybe we're missing some type definitions for it.

The tests are passing at HEAD on CI. I wonder if the tests execute this code.

**Comment by dmytrokyrychuk** [comment]
The tests are passing on this code too. Both `npm run tests` and `npm run goldens` pass.

**Comment by mhansen** [comment]
Thanks for the pull request. Why move so many files?

**Comment by dmytrokyrychuk** [comment]
Just one `tests` directory is moved :) The tests are moved to make room for `outDir` outside of `rootDir` (see tsconfig.json). The convention is to set `rootDir: "src"`. The tests were not in `src` in the `main` branch, so I moved them.

**Comment by mhansen** [comment]
What is .editorconfig? I haven't seen a file like that before.

Is it better to set a rootDir and an outDir than not? I am not very up to date with typescript. I had the tests separated from the "system under test" as a kind of logical separation before. I suppose it doesn't matter much. I'd just like to understand.

**Comment by mhansen** [comment]
General feedback: there are a lot of changes in here; splitting this up into smaller PRs or rewriting the commit messages to explain not just "what" you're doing but also the "why" would help me follow?

**Comment by simonmichael** [comment]
Thanks for working on this @dmytrokyrychuk. Hope you do get a chance to get back and split it up for easier merging.

**Pull request closed without merging**
